---
###############################################################################
# For hosts with no docker installed
###############################################################################
#roles:
#  - name: geerlingguy.docker
#    version: 3.1.2
###############################################################################
collections:
  - name: community.docker
    version: 1.5.0
