---
###############################################################################
# For hosts with no docker installed
###############################################################################
#- 
#  name: Install docker
#  include_role:
#    name: geerlingguy.docker
#  tags: [ "dockerserv" ]
###############################################################################
- name: Install Pip
  yum:
    name: python3-pip
  #become: true
  when: ansible_os_family == 'RedHat'
  tags: [ "dockerserv", "install" ]
- name: Install Python SDK
  pip:
    name: docker
  #become: true
  when: ansible_os_family == 'RedHat'
  tags: [ "dockerserv", "install" ]
- name: "Install Python SDK Ubuntu/Debian"       
  apt:
    pkg: python3-docker
    update_cache: yes
  when: ansible_os_family == 'Debian'
