---
###############################################################################
# For hosts with no docker installed
###############################################################################
#- 
#  name: Install docker
#  include_role:
#    name: geerlingguy.docker
#  tags: [ "dockerserv" ]
###############################################################################
-
  name: Install Pip CentOS
  yum:
    name: python3-pip
  when: ansible_os_family == 'RedHat'
  tags: [ "dockerserv", "install", "centos" ]
-
  name: Install Pip Ubuntu
  apt:
    pkg: python3-pip
    update_cache: yes
    state: present
  when: ansible_os_family == 'Debian'
  tags: [ "dockerserv", "install", "ubuntu" ]
-
  name: Install Python SDK
  pip:
    name: docker
  tags: [ "dockerserv", "install" ]
